##  http://localhost:8090/h2-console
server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:./ijuju_dev;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console